draw_timer_adjustment=3
show_cursor=true
                
;-------------------------------------------------------------------------

                .include "framework.s65"
                
;-------------------------------------------------------------------------

                .section zp
                .send zp

;-------------------------------------------------------------------------

                .section code

;-------------------------------------------------------------------------

fx_init_1: .proc
                jsr print_string

                .text 22,5
                .text 255

                .set_crtc 1,255

                .set_crtc 10,6

                lda #mode5_value(1,1,1,1)
                sta $5800

                lda #$b8        ;AUG 193, MasRef D.2-56
                ldx #0
                ldy #255
                jsr osbyte
                txa             ;A=video ULA control register value
                and #%00011111  ;mask out everything except the cursor
                                ;mode
                ;ora #%10100000  ;_ __ - undocumented
                ora #%11100000   ;____
                sta $fe20

                rts
                
                .pend

;-------------------------------------------------------------------------

fx_init_2: .proc
                rts
                .pend

;-------------------------------------------------------------------------

fx_update: .proc
                rts
                .pend

;-------------------------------------------------------------------------

                .align 256
fx_draw: .proc
                rts
                .pend
                
;-------------------------------------------------------------------------

                .send code
                