; VL6845/HD6845 difference:
;
; - VL6845 updates cursor flash timer at end of frame, when the
; vertical total is reached.
;
; - HD6845 updates cursor flash timer at bottom of screen, when the
; vertical displayed total is reached.
;
; Display shown has 16 frames: 15*2 rows, 1*7 rows. There are 16 ends
; of frame, and 1 bottom of screen. Cursor flash period is 16 frames.
;
; On VL6845, there's one flash period per CRTC frame, so you get 8
; displayed cursors and 8 hidden cursors. 15 of these are visible.
;
; On HD6845, there's one flash period per displayed TV field, so the
; cursor flashes as normal.

draw_timer_adjustment=24

;-------------------------------------------------------------------------

                .include "framework.s65"
                
;-------------------------------------------------------------------------

                .section zp
                .send zp

;-------------------------------------------------------------------------

                .section code

;-------------------------------------------------------------------------

fx_init_1: .proc
                ldx #0
-
                lda init_text,x
                jsr oswrch
                inx
                cpx #init_text.end-init_text
                bne -

                rts

init_text: .block
                .text 22,2
                .text "Hello"
end:
                .bend
                
                
                .pend

;-------------------------------------------------------------------------

fx_init_2: .proc
                ; reinstate cursor, which the framework helpfully (?)
                ; disables
                .set_crtc 10,%01000111
                rts
                .pend

;-------------------------------------------------------------------------

fx_update: .proc
                rts
                .pend

;-------------------------------------------------------------------------

                .align 256
fx_draw: .proc
                .set_crtc 6,3
                .set_crtc 4,1
                .set_crtc 7,255
                .for i=0,i<15,i+=1
                lda #mode2_palette(0,0);1+(i%5))
                sta video_palette
                .nops 16*128-6
                .next
                .set_crtc 6,0   ;induce bottom of screen
                .set_crtc 4,8
                .set_crtc 7,4
                rts
                .pend
                
;-------------------------------------------------------------------------

                .send code
                