draw_timer_adjustment=3

;-------------------------------------------------------------------------

                .include "framework.s65"
                
;-------------------------------------------------------------------------

                .section zp
                .send zp

;-------------------------------------------------------------------------

                .section code

;-------------------------------------------------------------------------

fx_init_1: .proc
                lda #22
                jsr oswrch
                lda #2
                jsr oswrch

                ; lda #23
                ; jsr oswrch
                
                ; lda #224
                ; jsr oswrch

                ; lda #1
                ; .rept 8
                ; jsr oswrch
                ; .next

                ; lda #32
                ; jsr oswrch

                ; lda #17
                ; jsr oswrch

                ; lda #4
                ; jsr oswrch
                
                ; lda #224
                ; jsr oswrch
                
                rts
                .pend

;-------------------------------------------------------------------------

fx_init_2: .proc
                rts
                .pend

;-------------------------------------------------------------------------

fx_update: .proc
                lda #mode2_palette(0,1)
                sta video_palette
                rts
                .pend

;-------------------------------------------------------------------------

                .align 256
fx_draw: .proc
                nop
                lda #mode2_palette(0,4)
                sta video_palette

                ; .nops 122

                lda #mode2_palette(0,3)
                sta video_palette

                rts
                .pend
                
;-------------------------------------------------------------------------

                .align 16
xtable: .fill 256,0

                .send code
                