;-------------------------------------------------------------------------
; This code is free software: you can redistribute it and/or modify it
; under the terms of the GNU General Public License as published by
; the Free Software Foundation, either version 3 of the License, or
; (at your option) any later version.

; This code is distributed in the hope that it will be useful, but
; WITHOUT ANY WARRANTY; without even the implied warranty of
; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
; General Public License for more details.

; You should have received a copy of the GNU General Public License
; along with this code. If not, see <https://www.gnu.org/licenses/>.
;-------------------------------------------------------------------------

draw_timer_adjustment=3

;-------------------------------------------------------------------------

                .include "framework.s65"
                
;-------------------------------------------------------------------------

                .section zp
                .send zp

;-------------------------------------------------------------------------

                .section code

;-------------------------------------------------------------------------

                ; lda #98
                ; sta $fe4f
                ; lda $fe4f
                ; asl a
                ; ror space_flags
                ; bit space_flags
                ; bmi space_done
                ; bvc space_done

fx_init_1: .proc
                jsr load_mode2_screen

                lda #0
                .for i=$3000,i<$3280,i+=8
                sta i
                .next

                rts
                
                .pend

;-------------------------------------------------------------------------

fx_init_2: .proc
                rts
                .pend

;-------------------------------------------------------------------------

fx_update: .proc
                lda #mode2_palette(0,1)
                sta video_palette
                rts
                .pend

;-------------------------------------------------------------------------

                .align 256
fx_draw: .proc
                lda #mode2_palette(0,4)
                sta video_palette

                ; .nops 122

                lda #mode2_palette(0,3)
                sta video_palette

                rts
                .pend
                
;-------------------------------------------------------------------------

                .align 16
xtable: .fill 256,0

                .send code
                