;-------------------------------------------------------------------------
; This code is free software: you can redistribute it and/or modify it
; under the terms of the GNU General Public License as published by
; the Free Software Foundation, either version 3 of the License, or
; (at your option) any later version.

; This code is distributed in the hope that it will be useful, but
; WITHOUT ANY WARRANTY; without even the implied warranty of
; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
; General Public License for more details.

; You should have received a copy of the GNU General Public License
; along with this code. If not, see <https://www.gnu.org/licenses/>.
;-------------------------------------------------------------------------

draw_timer_adjustment=3
show_cursor=false
                
;-------------------------------------------------------------------------

                .include "framework.s65"
                
;-------------------------------------------------------------------------

                .section zp
                .send zp

;-------------------------------------------------------------------------

                .section code

;-------------------------------------------------------------------------

fx_init_1: .proc
                jsr print_string

                .text 22,5
                .text 19,2,4,0,0,0
                .text 255

                .set_crtc 1,255

                ldx #7
-
                lda #mode5_value(1,1,1,1)
                sta $59f0,x

                lda #mode5_value(2,2,2,2)
                sta $59f8,x

                dex
                bpl -

                .set_crtc 10,7

                rts
                
                .pend

;-------------------------------------------------------------------------

fx_init_2: .proc
                rts
                .pend

;-------------------------------------------------------------------------

fx_update: .proc
                rts
                .pend

;-------------------------------------------------------------------------

                .align 256
fx_draw: .proc
                rts
                .pend
                
;-------------------------------------------------------------------------

                .send code
                