draw_timer_adjustment=0

                .include "framework.s65"

;-------------------------------------------------------------------------

                .section zp
                .send zp

;-------------------------------------------------------------------------

                .section code

;-------------------------------------------------------------------------

fx_init_1: .proc
                jsr load_mode2_screen
                rts
                .pend

;-------------------------------------------------------------------------

fx_init_2: .proc
                rts
                .pend

;-------------------------------------------------------------------------

fx_update: .proc
                ; .set_crtc 4,38  ;usual Mode 2 value
                rts
                .pend

;-------------------------------------------------------------------------

fx_draw: .proc
                jsr cycles_wait_128
                .set_crtc 4,38
                
                jsr cycles_wait_1024
                jsr cycles_wait_1024

                .set_mode2_palette 0,1
                jsr cycles_wait_128
                .set_mode2_palette 0,0

                ; HD6845 - screen goes nuts, as expected
                ; VL6845 - ignored, as row counter is not 0
                
                .set_crtc 4,$ff
                
                lda #2
-
                bit $fe4d
                beq -
                sta $fe4d
                
                rts
                .pend

;-------------------------------------------------------------------------

                .send code
                