draw_timer_adjustment=0

;-------------------------------------------------------------------------

                .include "framework.s65"
                
;-------------------------------------------------------------------------

                .section zp
                .send zp

;-------------------------------------------------------------------------

                .section code

;-------------------------------------------------------------------------

fx_init_1: .proc
                jsr load_mode2_screen

                ; lda #12
                ; jsr oswrch

                rts
                .pend

;-------------------------------------------------------------------------

fx_init_2: .proc
                rts
                .pend

;-------------------------------------------------------------------------

fx_update: .proc
                lda #mode2_palette(0,1)
                sta video_palette
                
                lda #mode2_palette(7,7)
                sta video_palette

                rts
                
                .pend

;-------------------------------------------------------------------------

                .align 256
fx_draw: .proc
                .set_crtc 6,8
                
                ; Wait for row 1.
                .nops 18*128
                
                lda #mode2_palette(0,4)
                sta video_palette

                ; The row counter doesn't compare equal, so the
                ; visible display continues, even past the usual 32
                ; limit, until it reaches the vertical total.
                .set_crtc 6,1

                rts
                .pend
                
;-------------------------------------------------------------------------
                
                .send code
                