draw_timer_adjustment=0

;-------------------------------------------------------------------------

                .include "framework.s65"
                
;-------------------------------------------------------------------------

                .section zp
routine_index: .fill 1
space_flags: .fill 1
                .send zp

;-------------------------------------------------------------------------

                .section code

;-------------------------------------------------------------------------

fx_init_1: .proc
                jsr load_mode2_screen

                rts
                .pend

;-------------------------------------------------------------------------

fx_init_2: .proc
                rts
                .pend

;-------------------------------------------------------------------------

fx_update: .proc
                lda #mode2_palette(0,1)
                sta video_palette
                
                lda #mode2_palette(7,7)
                sta video_palette

                ; Make the screen a bit shorter...
                .crtc 6,24

                rts
                
                .pend

;-------------------------------------------------------------------------

                .align 256
fx_draw: .proc
                ; Wait for row 1.
                .nops 9*128
                
                lda #mode2_palette(0,4)
                sta video_palette
                
                ; The row counter won't compare equal to this value at
                ; this point...
                .crtc 6,0

                ; The old value must have been stored somewhere, as
                ; the visible area remains its original height.

                rts
                .pend
                
;-------------------------------------------------------------------------
                
                .send code
                