draw_timer_adjustment=0

;-------------------------------------------------------------------------

                .include "framework.s65"
                
;-------------------------------------------------------------------------

                .section zp
                .send zp

                .section code

;-------------------------------------------------------------------------

fx_init_1: .proc
                jsr load_mode2_screen
                rts
                .pend

;-------------------------------------------------------------------------

fx_init_2: .proc
                rts
                .pend

;-------------------------------------------------------------------------

fx_update: .proc
                lda #mode2_palette(0,1)
                sta video_palette
                
                lda #mode2_palette(7,7)
                sta video_palette

                ; Mode 2 defaults...
                .crtc 6,32

                rts
                
                .pend

;-------------------------------------------------------------------------

                .align 256
fx_draw: .proc
                .nops 3*128
                
                lda #mode2_palette(0,7)
                sta video_palette
                
                .nops 40-16-6

                .crtc 6,0

                ; display now off...

                .nops 3*128

                .crtc 6,32

                ; display no longer on...

                rts
                .pend
                
;-------------------------------------------------------------------------
                
                .send code
                